# Generated by Django 4.0.6 on 2022-07-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0002_alter_customuser_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
