# Generated by Django 4.0.6 on 2022-08-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0005_posts_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
    ]
